FROM alpine:3.17.0

#RUN go install github.com/pressly/goose/v3/cmd/goose@latest
WORKDIR /app

RUN apk update && \
  apk upgrade && \
  apk add bash && \
  rm -rf /var/cache/apk/*

ADD https://github.com/pressly/goose/releases/download/v3.16.0/goose_linux_arm64 /bin/goose
RUN chmod +x /bin/goose

ADD src/migrations migrations

ENTRYPOINT ["/bin/sh", "-c", "/bin/goose -v -dir migrations postgres \"postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable\" up"]
